[package]
name = "haddock"
version = "0.2.0"
authors = ["Hans Blom"]
edition = "2018"

[dependencies]
ctrlc = "3.1.1"
rand = "0.6.1"
lazy_static = "1.1.0"
criterion = "0.2.7"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "my_benchmark"
harness = false